facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    templates_root: src/main/resources/templates/
  data:
    mongodb:
      uri: mongodb://JULY:JULY@localhost:27017/july
  resources:
    chain:
      enabled: true

config:
  json:
    path: classpath:static/config/config.json

multipart:
  maxFileSize: 100MB
  max-request-size: 100MB
#spring.data.mongodb.uri: mongodb://<user>:<passwd>@<url>:<port>/<dbname>